### ISSUE TITLE
unable to launch

### ISSUE THREAD

**Issue by boistordu** [sumanthratna/soundcloud9000#21]
under fedora34

```
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': /usr/local/lib64/gems/ruby/audite-0.4.0/portaudio.so: undefined symbol: mpg123_plain_strerror - /usr/local/lib64/gems/ruby/audite-0.4.0/portaudio.so (LoadError)
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/share/gems/gems/audite-0.4.0/lib/audite.rb:1:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000/models/player.rb:1:in `<top (required)>'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000/controllers/player_controller.rb:2:in `require_relative'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000/controllers/player_controller.rb:2:in `<top (required)>'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000/application.rb:8:in `require_relative'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000/application.rb:8:in `<top (required)>'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000.rb:2:in `require_relative'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/lib/soundcloud9000.rb:2:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/share/gems/gems/soundcloud9000-0.1.3/bin/soundcloud9000:7:in `<top (required)>'
	from /usr/local/bin/soundcloud9000:23:in `load'
	from /usr/local/bin/soundcloud9000:23:in `<main>'

```

**Comment by y4my4my4m** [comment]
same issue here

**Comment by sumanthratna** [comment]
@boistordu  @y4my4my4m can you try the following? 
1. `gem uninstall audite`
2. `gem install --user audite -- --with-ldflags="-lmpg123"`

**Comment by y4my4my4m** [comment]
@sumanthratna 

no luck, this happens when i launch it now
https://gist.github.com/y4my4my4m/28a01c82531ed2beccf9cec2b5880bda

**Comment by sumanthratna** [comment]
> no luck, this happens when i launch it now https://gist.github.com/y4my4my4m/28a01c82531ed2beccf9cec2b5880bda

in `/usr/share/alsa/alsa.conf` there should be some lines that look like the following: 
```
pcm.rear cards.pcm.rear
pcm.center_lfe cards.pcm.center_lfe
pcm.side cards.pcm.side
...
```
can you try commenting out all the appropriate lines in `alsa.conf` (based on the error message you sent)?

**Comment by y4my4my4m** [comment]
@sumanthratna 
ive commented them out, restarted alsa with `sudo alsactl restore` and relaunched soundcloud9000 but same issue

Could it be that it doesn't support `pipewire` ? 

Edit:
By the way, i've commented more than these three, the ones that were appearing in the message. They dont appear anymore when launching but its still the same segfault error so im not sure it's related to alsa devices

`ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
